// Task
// Your task is to make a function that can take any non-negative integer as a argument and return it with its digits in descending order. Essentially, rearrange the digits to create the highest possible number.

// Specification
// descendingOrder(num)
// Parameters
// num: Number - unsigned integer

// Return Value
// Number - A new number generated by sorting the digits of num in descending order.

// Constraints
// num will always be a valid integer.

// num will always be greater than zero.

// Examples
// num	Return Value
// 21445	54421
// 145263	654321
// 1254859723	9875543221

const descendingOrder = num => {
    return parseInt((num+'').split('').sort().reverse().join(''))
};