// Task
// You have function with one side of the DNA, you need to get the other complementary side. The DNA strand may be empty if there is no DNA at all. In this case, you can simple return the empty string.

// Specification
// dnaComplement(dna)
// Parameters
// dna: String - DNA strand

// Return Value
// String - A new string generated by returning the complement of the input strand.

// Constraints
// It will always be a string, but it might be empty.

// It will never be null/nil or undefined.

// Examples
// dna	Return Value
// "A"	"T"
// "T"	"A"
// "C"	"G"
// "G"	"C"
// "ATTGC"	"TAACG"
// ""	""

const dnaComplement = dna => {
    var letras = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'};
      var array = [];
      for (var i=0; i < dna.length; i++) {
          array[i] = letras[dna[i]];
      }
      return array.join('');
};

